

#spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
#spring.datasource.username=employee_user
#spring.datasource.password=employee_password
# ===============================
# Local Database
# ===============================
#spring.datasource.url=jdbc:h2:file:./app/data/employee_db
##spring.datasource.url=jdbc:h2:file:/home/amol/Desktop/employee_transaction/employee_artifact/data/employee_db
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



# ===============================
# Application
# ===============================
spring.application.name=employee_artifact
server.port=8082

# ===============================
# Azure PostgreSQL Database
# ===============================server.port=8080
spring.datasource.url=jdbc:postgresql://employee-db.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=amol
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernateserver.port=8080
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Connection Pool
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000